language: elixir

elixir:
  - '1.7.4'
  - '1.8.2'

env:
  - MIX_ENV=test

script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - MIX_ENV=docs mix do deps.get, inch.report
