on:
- push
- pull_request

jobs:
  test:
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Compatibility info can be found at
        # https://github.com/erlef/setup-beam?tab=readme-ov-file#compatibility-between-operating-system-and-erlangotp
        include:
          - elixir: "1.11.4"
            otp: "24"
            os: ubuntu-24.04
          - elixir: "1.12.3"
            otp: "24"
            os: ubuntu-24.04
          - elixir: "1.13.4"
            otp: "24"
            os: ubuntu-24.04
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix compile
      - run: mix coveralls.json
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
